export const Locationtype = [
  { value: "Add New", label: "Add Custom to List" },
  { value: "Apartment Parking", label: "Apartment Parking" },
  { value: "Banquet Halls", label: "Banquet Halls" },
  { value: "Beach House", label: "Beach House" },
  { value: "BT roads (open roads)", label: "BT roads (open roads)" },
  { value: "Bus Stand", label: "Bus Stand" },
  { value: "Civil Court", label: "Civil Court" },
  { value: "College", label: "College" },
  { value: "Convention Centres", label: "Convention Centres" },
  { value: "Corporate Office", label: "Corporate Office" },
  { value: "Dhaba", label: " Dhaba" },
  { value: "Event auditoriums", label: "Event auditoriums" },
  { value: "Factory", label: "Factory" },
  { value: "Farmhouse", label: " Farmhouse" },
  { value: "Farmland", label: "Farmland" },
  { value: "Forest", label: "Forest" },
  { value: "Forest Stay", label: "Forest Stay" },
  { value: "Gated Community", label: "Gated Community" },
  { value: "Hospital", label: "Hospital" },
  { value: "Hotel", label: "Hotel" },
  { value: "Hotel Stay", label: "Hotel Stay" },
  { value: "Industry", label: "Industry" },
  { value: "Jail", label: "Jail" },
  { value: "Lake House", label: "Lake House" },
  { value: "Lake Stay", label: "Lake Stay" },
  { value: "Lakes", label: "Lakes" },
  { value: "Manduva House", label: "Manduva House" },
  { value: "Movie Theatres", label: "Movie Theatres" },
  { value: "Police station", label: "Police station" },
  { value: "Pubs", label: "Pubs" },
  { value: "Railway station", label: "Railway station" },
  { value: "Resorts", label: "Resorts" },
  { value: "Restaurants", label: "Restaurants" },
  { value: "Rich house", label: "Rich house" },
  { value: "School", label: "School" },
  { value: "Shooting floors", label: "Shooting floors" },
  { value: "Shopping Malls", label: "Shopping Malls" },
  { value: "Sports auditoriums", label: "Sports auditoriums" },
  { value: "Studio Floors", label: "Studio Floors" },
  { value: "TV Stations", label: "TV Stations" },
  { value: "Village atmosphere", label: "Village atmosphere" },
  { value: "Weekend Farming", label: "Weekend Farming" },
  { value: "Wooden house", label: "Wooden house" },
];

export const AmenitiesType = [
  { value: "Air Conditioning", label: "Air Conditioning", selected: false },
  {
    value: "Access to public transportation",
    label: " Access to public transportation",
    selected: false,
  },
  {
    value: "All utilities included",
    label: " All utilities included",
    selected: false,
  },
  { value: "Balcony", label: " Balcony", selected: false },
  { value: "Bark Parks", label: " Bark Parks", selected: false },
  { value: "Bike Parking", label: " Bike Parking", selected: false },
  { value: "Business Center", label: " Business Center", selected: false },
  { value: "Cable ready", label: " Cable ready", selected: false },
  {
    value: "Ceiling Fans in All Bedrooms",
    label: " Ceiling Fans in All Bedrooms",
    selected: false,
  },
  {
    value: "Clubhouse with Lounge Seating",
    label: " Clubhouse with Lounge Seating",
    selected: false,
  },
  { value: "Co-Working Spaces", label: " Co-Working Spaces", selected: false },
  { value: "Community Lounge", label: " Community Lounge", selected: false },
  {
    value: "Computer Desks In Each Unit",
    label: " Computer Desks In Each Unit",
    selected: false,
  },
  { value: "Conference Rooms", label: " Conference Rooms", selected: false },
  { value: "Courtyard", label: " Courtyard", selected: false },
  { value: "Covered Parking", label: " Covered Parking", selected: false },
  {
    value: "Custom Cabinetry and Large Kitchen Islands",
    label: " Custom Cabinetry and Large Kitchen Islands",
    selected: false,
  },
  {
    value: "Custom Colored Accent walls",
    label: " Custom Colored Accent walls",
    selected: false,
  },
  { value: "Dining Room", label: " Dining Room", selected: false },
  { value: "Dishwasher", label: " Dishwasher", selected: false },
  { value: "Dual Sinks", label: " Dual Sinks", selected: false },
  { value: "Fire Pits", label: " Fire Pits", selected: false },
  { value: "Fitness Center", label: " Fitness Center", selected: false },
  {
    value: "Fitness Center – Technogym Equipped",
    label: " Fitness Center – Technogym Equipped",
    selected: false,
  },
  { value: "Food Shopping", label: " Food Shopping", selected: false },
  {
    value: "Frameless Shower Doors",
    label: " Frameless Shower Doors",
    selected: false,
  },
  {
    value: "Furnished apartments",
    label: " Furnished apartments",
    selected: false,
  },
  { value: "Garages", label: " Garages", selected: false },
  { value: "Gated Access", label: " Gated Access", selected: false },
  { value: "Golf Simulators", label: " Golf Simulators", selected: false },
  {
    value: "Greater Amounts of Storage",
    label: " Greater Amounts of Storage",
    selected: false,
  },
  { value: "Grilling Pavilion", label: " Grilling Pavilion", selected: false },
  {
    value: "Hair and Nail Salons",
    label: " Hair and Nail Salons",
    selected: false,
  },
  {
    value: "High-speed internet access",
    label: " High-speed internet access",
    selected: true,
  },
  {
    value: "TV Included",
    label: "TV Included",
    selected: false,
  },
  {
    value: "Wine Cellar",
    label: "Wine Cellar",
    selected: false,
  },
  { value: " Wifi", label: "Wifi", selected: true },
  {
    value: "In-unit washer and dryer",
    label: " In-unit washer and dryer",
    selected: false,
  },
  { value: "Indoor Basketball", label: " Indoor Basketball", selected: false },
  {
    value: "Indoor Mail Boxes and Mobile Package Service Alerts",
    label: " Indoor Mail Boxes and Mobile Package Service Alerts",
    selected: false,
  },
  { value: "Lake", label: " Lake", selected: false },
  { value: "Laundry Facility", label: " Laundry Facility", selected: false },
  { value: "Library", label: " Library", selected: false },
  { value: "Luxury Bathrooms", label: " Luxury Bathrooms", selected: false },
  { value: "Movie Theater", label: " Movie Theater", selected: false },
  {
    value: "Multi-Purpose Game Room",
    label: " Multi-Purpose Game Room",
    selected: false,
  },
  { value: "Online Payments", label: " Online Payments", selected: false },
  {
    value: "Oversized Balconies Over Looking Pool",
    label: " Oversized Balconies Over Looking Pool",
    selected: false,
  },
  { value: "Pet friendly", label: " Pet friendly", selected: false },
  { value: "Pet-Friendly", label: " Pet-Friendly", selected: false },
  { value: "Pets allowed", label: " Pets allowed", selected: false },
  {
    value: "Plush Carpeting in Bedrooms",
    label: " Plush Carpeting in Bedrooms",
    selected: false,
  },
  {
    value: "Private Balconies and Patios",
    label: " Private Balconies and Patios",
    selected: false,
  },
  {
    value: "Private Bedrooms and Bathrooms",
    label: " Private Bedrooms and Bathrooms",
    selected: false,
  },
  {
    value: "Private Meeting Rooms",
    label: " Private Meeting Rooms",
    selected: false,
  },
  {
    value: "Quartz Countertops with Tile Backsplash",
    label: " Quartz Countertops with Tile Backsplash",
    selected: false,
  },
  {
    value: "Resort-Style Pools",
    label: " Resort-Style Pools",
    selected: false,
  },
  { value: "Roof-Top Terraces", label: " Roof-Top Terraces", selected: false },
  {
    value: "Screening Room with 128” Projector screen",
    label: " Screening Room with 128” Projector screen",
    selected: false,
  },
  {
    value: "Some utilities included",
    label: " Some utilities included",
    selected: false,
  },
  {
    value: "Sound-Proof Music JamRoom with Piano",
    label: " Sound-Proof Music JamRoom with Piano",
    selected: false,
  },
  { value: "Spa", label: " Spa", selected: false },
  {
    value: "Spacious Walk-In Closets",
    label: " Spacious Walk-In Closets",
    selected: false,
  },
  {
    value: "Stainless Steel Appliances",
    label: " Stainless Steel Appliances",
    selected: false,
  },
  { value: "Sun Deck", label: " Sun Deck", selected: false },
  { value: "Sun Tanning Salon", label: " Sun Tanning Salon", selected: false },
  { value: "Swimming Pool", label: " Swimming Pool", selected: false },
  { value: "Swimming pool", label: " Swimming pool", selected: false },
  { value: "Toddler Room", label: " Toddler Room", selected: false },
  {
    value: "Utilities Included",
    label: " Utilities Included",
    selected: true,
  },
  { value: "Valet Parking", label: " Valet Parking", selected: false },
  {
    value: "Washer and dryer connections",
    label: " Washer and dryer connections",
    selected: false,
  },
  { value: "Washer and Dryers", label: " Washer and Dryers", selected: false },
  {
    value: "Wireless internet access",
    label: " Wireless internet access",
    selected: false,
  },
  {
    value: "Wood-Style Flooring in Living and Dining Areas",
    label: " Wood-Style Flooring in Living and Dining Areas",
    selected: false,
  },
  {
    value: "“Smart” Sensors that Control Lighting and Temperature",
    label: " “Smart” Sensors that Control Lighting and Temperature",
    selected: false,
  },
];

// features contanst

export const FeatureConstant = [
  { value: "Alarm system", label: " Alarm system" },
  {
    value: "Architectural details, such as crown moldings, chair rails, etc.",
    label: " Architectural details, such as crown moldings, chair rails, etc.",
  },
  {
    value: "Builder’s name, if well known in the area",
    label: " Builder’s name, if well known in the area",
  },
  { value: "Central air conditioning", label: " Central air conditioning" },
  { value: "Deck", label: " Deck" },
  { value: "Energy efficiency", label: " Energy efficiency" },
  { value: "Exercise room", label: " Exercise room" },
  { value: "Exterior lighting", label: " Exterior lighting" },
  { value: "Finished basement", label: " Finished basement" },
  {
    value: "Fireplaces and wood-burning stoves",
    label: " Fireplaces and wood-burning stoves",
  },
  {
    value: "Garage – heated, three-car, etc.",
    label: " Garage – heated, three-car, etc.",
  },
  {
    value: "Granite countertops in kitchen",
    label: " Granite countertops in kitchen",
  },
  { value: "Great for entertaining", label: " Great for entertaining" },
  {
    value: "Heat pump or other energy-efficient systems",
    label: " Heat pump or other energy-efficient systems",
  },
  { value: "Home theater", label: " Home theater" },
  { value: "Hot tub", label: " Hot tub" },
  { value: "In-ground pool", label: " In-ground pool" },
  {
    value: "In-law or extra apartment with rental potential",
    label: " In-law or extra apartment with rental potential",
  },
  {
    value: "Kitchen – gourmet, great for entertaining, etc.",
    label: " Kitchen – gourmet, great for entertaining, etc.",
  },
  { value: "Landscaping", label: " Landscaping" },
  { value: "Light-filled or bright", label: " Light-filled or bright" },
  {
    value: "Master suite with separate bath",
    label: " Master suite with separate bath",
  },
  { value: "Move-in condition", label: " Move-in condition" },
  { value: "New bathrooms or kitchen", label: " New bathrooms or kitchen" },
  {
    value:
      "New improvements, such as roof, furnace, electrical service or wiring",
    label:
      " New improvements, such as roof, furnace, electrical service or wiring",
  },
  { value: "New septic system", label: " New septic system" },
  { value: "Open floor plan", label: " Open floor plan" },
  {
    value:
      "Outbuildings that can be used for shops, storage, rental income, etc.",
    label:
      " Outbuildings that can be used for shops, storage, rental income, etc.",
  },
  {
    value: "Pride of ownership that shows",
    label: " Pride of ownership that shows",
  },
  {
    value: "Solar heating or electrical",
    label: " Solar heating or electrical",
  },
  {
    value: "Square footage (if it represents a good value for your price)",
    label: " Square footage (if it represents a good value for your price)",
  },
  { value: "Town sewers", label: " Town sewers" },
  {
    value: "Upscale appliances that appeal to luxury-oriented buyers",
    label: " Upscale appliances that appeal to luxury-oriented buyers",
  },
  {
    value: "Views of mountains, lakes, sunsets, sunrises",
    label: " Views of mountains, lakes, sunsets, sunrises",
  },
  {
    value: "Window – new and energy efficient",
    label: " Window – new and energy efficient",
  },
  { value: "Wood floors", label: " Wood floors" },
];
